// <auto-generated />
using System;
using Krik.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Krik.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Krik.Api.Entities.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Krik.Api.Entities.CommissionBracket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CommissionPct")
                        .HasColumnType("numeric");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<decimal?>("KpiPctMax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("KpiPctMin")
                        .HasColumnType("numeric");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PositionCode", "ContractType", "EffectiveFrom");

                    b.ToTable("CommissionBrackets");
                });

            modelBuilder.Entity("Krik.Api.Entities.KrikUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("StoreId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("StoreId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Krik.Api.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Krik.Api.Entities.StaffDailyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Customers")
                        .HasColumnType("integer");

                    b.Property<decimal>("HoursAfternoon")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HoursEvening")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HoursExtra")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HoursMorning")
                        .HasColumnType("numeric");

                    b.Property<int>("Orders")
                        .HasColumnType("integer");

                    b.Property<int>("Products")
                        .HasColumnType("integer");

                    b.Property<decimal>("RevenueAfternoon")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RevenueEvening")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RevenueMorning")
                        .HasColumnType("numeric");

                    b.Property<Guid>("StoreStaffId")
                        .HasColumnType("uuid");

                    b.Property<int>("TryOns")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("StoreStaffId", "WorkDate")
                        .IsUnique();

                    b.ToTable("StaffDailyEntries");
                });

            modelBuilder.Entity("Krik.Api.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Krik.Api.Entities.StoreDailySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ChannelRevenueAfternoon")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ChannelRevenueEvening")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ChannelRevenueMorning")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TongDoanhThuHeThong")
                        .HasColumnType("numeric");

                    b.Property<int>("StoreCustomers")
                        .HasColumnType("integer");

                    b.Property<decimal>("StoreDayKpiTarget")
                        .HasColumnType("numeric");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<int>("StoreOrders")
                        .HasColumnType("integer");

                    b.Property<int>("StoreProducts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDayLocked")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("StoreId", "WorkDate")
                        .IsUnique();

                    b.ToTable("StoreDailySummaries");
                });

            modelBuilder.Entity("Krik.Api.Entities.StoreMonthlyKpiConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DayRatiosJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMonthLocked")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MonthlyTargetAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("ShiftRatiosJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WeekRatiosJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("YearMonth")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("StoreId", "YearMonth")
                        .IsUnique();

                    b.ToTable("StoreMonthlyKpiConfigs");
                });

            modelBuilder.Entity("Krik.Api.Entities.StoreStaff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("LinkedUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TeamBonusBase")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("LinkedUserId");

                    b.HasIndex("StoreId", "StaffCode")
                        .IsUnique();

                    b.ToTable("StoreStaff");
                });

            modelBuilder.Entity("Krik.Api.Entities.UserArea", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "AreaId");

                    b.HasIndex("AreaId");

                    b.ToTable("UserAreas");
                });

            modelBuilder.Entity("Krik.Api.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Krik.Api.Entities.KrikUser", b =>
                {
                    b.HasOne("Krik.Api.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Krik.Api.Entities.StaffDailyEntry", b =>
                {
                    b.HasOne("Krik.Api.Entities.StoreStaff", "StoreStaff")
                        .WithMany("DailyEntries")
                        .HasForeignKey("StoreStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreStaff");
                });

            modelBuilder.Entity("Krik.Api.Entities.Store", b =>
                {
                    b.HasOne("Krik.Api.Entities.Area", "Area")
                        .WithMany("Stores")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Krik.Api.Entities.StoreDailySummary", b =>
                {
                    b.HasOne("Krik.Api.Entities.Store", "Store")
                        .WithMany("DailySummaries")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Krik.Api.Entities.StoreMonthlyKpiConfig", b =>
                {
                    b.HasOne("Krik.Api.Entities.Store", "Store")
                        .WithMany("MonthlyKpiConfigs")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Krik.Api.Entities.StoreStaff", b =>
                {
                    b.HasOne("Krik.Api.Entities.KrikUser", "LinkedUser")
                        .WithMany()
                        .HasForeignKey("LinkedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Krik.Api.Entities.Store", "Store")
                        .WithMany("StaffMembers")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinkedUser");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Krik.Api.Entities.UserArea", b =>
                {
                    b.HasOne("Krik.Api.Entities.Area", "Area")
                        .WithMany("UserAreas")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Krik.Api.Entities.KrikUser", "User")
                        .WithMany("UserAreas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Krik.Api.Entities.UserRole", b =>
                {
                    b.HasOne("Krik.Api.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Krik.Api.Entities.KrikUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Krik.Api.Entities.Area", b =>
                {
                    b.Navigation("Stores");

                    b.Navigation("UserAreas");
                });

            modelBuilder.Entity("Krik.Api.Entities.KrikUser", b =>
                {
                    b.Navigation("UserAreas");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Krik.Api.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Krik.Api.Entities.Store", b =>
                {
                    b.Navigation("DailySummaries");

                    b.Navigation("MonthlyKpiConfigs");

                    b.Navigation("StaffMembers");
                });

            modelBuilder.Entity("Krik.Api.Entities.StoreStaff", b =>
                {
                    b.Navigation("DailyEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
